### ISSUE TITLE
Docker installation?

### ISSUE THREAD

**Issue by somedevreally** [teddit-net/teddit#1]
will there be a docker installation?

thanks for this UI

**Comment by somedevreally** [comment]
am getting error while building the container
```
Building teddit

ERROR: error fetching: fatal: couldn't find remote ref master

: exit status 128

```

**Comment by somedevreally** [comment]
my docker-compose is 

```
teddit:
    build: https://github.com/teddit-net/teddit.git
    container_name: teddit
    ports:
      - '8080:8080'
    restart: always
```
